### ISSUE TITLE
Promise rejections are caught without warning or error.

### ISSUE THREAD

**Issue by pl12133** [synacor/wiretie#7]
When an `async` function returns a rejected `Promise`, it is [caught here](https://github.com/synacor/wiretie/blob/master/src/index.js#L179-L188) in order to set the `rejected` prop value.

This works well for displaying an error state in a component, but it also swallows the Promise rejection and continues to resolve the Promise chain. 

Normally a Promise rejected in this manner would result in an `unhandledrejection` event being fired and an error printing itself to the console. However because the error is already caught, the error message is swallowed without being printed to the console. Swallowed errors are difficult to track down, and make it appear that your application is not failing when it really is.

I would like to see one of these options for a resolution:

1. Call `console.error` with the error from `catch`.
2. Return a rejected Promise from `catch`, causing an `unhandledrejection` event.

Let me know if you think it is worthwhile to make these errors more obvious, thanks.

**Comment by developit** [comment]
I'm a fan of #2 personally, since that lets people hook them via `unhandledrejection`.

**Comment by pl12133** [comment]
I also would prefer approach 2, so I've opened up #8 to go ahead with that fix.
